"""Add preferred_places to user_preferences

Revision ID: 14ae4b09422c
Revises:
Create Date: 2026-01-06 14:18:56.765340

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14ae4b09422c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("service_name", sa.String(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=True),
        sa.Column("calls_count", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=True),
        sa.Column("request_params", sa.String(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column(
            "called_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_usage_id"), "api_usage", ["id"], unique=False)
    op.create_index(
        "ix_api_usage_user_service_time",
        "api_usage",
        ["user_id", "service_name", "called_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_cache_entries_expires_at"), table_name="cache_entries")
    op.drop_index(op.f("ix_cache_entries_id"), table_name="cache_entries")
    op.drop_index(op.f("ix_cache_entries_key"), table_name="cache_entries")
    op.drop_index(op.f("ix_cache_entries_key_expires"), table_name="cache_entries")
    op.drop_table("cache_entries")
    op.add_column("user_preferences", sa.Column("preferred_places", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_preferences", "preferred_places")
    op.create_table(
        "cache_entries",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("key", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("value", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("access_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "last_accessed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cache_entries_pkey")),
    )
    op.create_index(
        op.f("ix_cache_entries_key_expires"), "cache_entries", ["key", "expires_at"], unique=False
    )
    op.create_index(op.f("ix_cache_entries_key"), "cache_entries", ["key"], unique=True)
    op.create_index(op.f("ix_cache_entries_id"), "cache_entries", ["id"], unique=False)
    op.create_index(
        op.f("ix_cache_entries_expires_at"), "cache_entries", ["expires_at"], unique=False
    )
    op.drop_index("ix_api_usage_user_service_time", table_name="api_usage")
    op.drop_index(op.f("ix_api_usage_id"), table_name="api_usage")
    op.drop_table("api_usage")
    # ### end Alembic commands ###
