"""Change lot_size from Integer to Float

Revision ID: f277f7865e47
Revises: 14ae4b09422c
Create Date: 2026-01-12 13:04:24.803251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f277f7865e47"
down_revision: Union[str, None] = "14ae4b09422c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cache_entries",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("custom_locations", "priority", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "custom_locations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "properties",
        "lot_size",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "properties",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "property_enrichments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("saved_properties", "is_favorite", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("saved_properties", "is_archived", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "saved_properties", "viewed_in_person", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "saved_properties",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_preferences", "notify_new_listings", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "user_preferences", "notify_price_changes", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "user_preferences",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("user_preferences", "workplace_longitude")
    op.drop_column("user_preferences", "workplace_latitude")
    op.drop_column("user_preferences", "workplace_address")
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "user_preferences",
        sa.Column("workplace_address", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user_preferences",
        sa.Column(
            "workplace_latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user_preferences",
        sa.Column(
            "workplace_longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "user_preferences",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_preferences", "notify_price_changes", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "user_preferences", "notify_new_listings", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "saved_properties",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "saved_properties", "viewed_in_person", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column("saved_properties", "is_archived", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("saved_properties", "is_favorite", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "property_enrichments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "properties",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "properties",
        "lot_size",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "custom_locations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("custom_locations", "priority", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "cache_entries",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
